// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tqOcPk2WGPU-Y5KLXezbbWvuVEtan3U',
    appId: '1:893379584608:web:762ad991795c781c071905',
    messagingSenderId: '893379584608',
    projectId: 'transferr-gestao-dev',
    authDomain: 'transferr-gestao-dev.firebaseapp.com',
    storageBucket: 'transferr-gestao-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlNYDZaEaInIexX8mEoM_cKFnuXvYgqQ',
    appId: '1:893379584608:android:25ef44854c6cbde0071905',
    messagingSenderId: '893379584608',
    projectId: 'transferr-gestao-dev',
    storageBucket: 'transferr-gestao-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG6njaioTesmIrwRSO-OiStqejySnZ2rY',
    appId: '1:893379584608:ios:d4a9c60e5ff43530071905',
    messagingSenderId: '893379584608',
    projectId: 'transferr-gestao-dev',
    storageBucket: 'transferr-gestao-dev.firebasestorage.app',
    iosBundleId: 'com.example.transferr',
  );

}